# QuickMorphismStyleHelpers.cmake
# Helper functions for using QuickMorphism style in Qt applications

# Function to automatically configure QuickMorphism style path
function(configure_quickmorphism_style target_name)
    # Parse arguments
    set(options INSTALL_IN_QT_DIR)
    set(oneValueArgs CUSTOM_STYLE_DIR)
    set(multiValueArgs "")
    cmake_parse_arguments(QM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    
    # Determine the style directory
    if(QM_INSTALL_IN_QT_DIR)
        # Use Qt's standard location
        get_target_property(QT_QMAKE_EXECUTABLE Qt6::qmake IMPORTED_LOCATION)
        execute_process(COMMAND ${QT_QMAKE_EXECUTABLE} -query QT_INSTALL_QML 
                        OUTPUT_VARIABLE QT_QML_DIR 
                        OUTPUT_STRIP_TRAILING_WHITESPACE)
        set(style_path "${QT_QML_DIR}/QtQuick/Controls")
    elseif(QM_CUSTOM_STYLE_DIR)
        # Use custom directory
        set(style_path "${QM_CUSTOM_STYLE_DIR}")
    else()
        # Default: use QuickMorphism build directory
        set(style_path "${QuickMorphism_BINARY_DIR}/qml")
    endif()
    
    # Generate configuration header
    set(config_header_content 
"// Auto-generated by QuickMorphism CMake configuration
#ifndef QUICKMORPHISM_CONFIG_H
#define QUICKMORPHISM_CONFIG_H

#define QUICKMORPHISM_STYLE_PATH \"${style_path}\"

#include <QQmlApplicationEngine>
#include <QQuickStyle>

namespace QuickMorphism {
    inline void setupStyle(QQmlApplicationEngine& engine) {
        // Add QuickMorphism style path to import paths
        engine.addImportPath(QStringLiteral(QUICKMORPHISM_STYLE_PATH));
        
        // Set QuickMorphism as the default style
        QQuickStyle::setStyle(QStringLiteral(\"QuickMorphism\"));
    }
    
    inline void setupStyle(QQmlApplicationEngine& engine, const QString& customPath) {
        // Add custom style path to import paths
        engine.addImportPath(customPath);
        
        // Set QuickMorphism as the default style
        QQuickStyle::setStyle(QStringLiteral(\"QuickMorphism\"));
    }
}

#endif // QUICKMORPHISM_CONFIG_H
")
    
    # Write the configuration header
    set(config_header_path "${CMAKE_CURRENT_BINARY_DIR}/quickmorphism_config.h")
    file(WRITE "${config_header_path}" "${config_header_content}")
    
    # Add the header to the target's include directories
    target_include_directories(${target_name} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
    
    # Print configuration information
    message(STATUS "QuickMorphism configured for target '${target_name}':")
    message(STATUS "  Style path: ${style_path}")
    message(STATUS "  Configuration header: ${config_header_path}")
    message(STATUS "  Usage: #include \"quickmorphism_config.h\" and call QuickMorphism::setupStyle(engine)")
endfunction()

# Function to add QuickMorphism dependency to a target
function(add_quickmorphism_dependency target_name)
    # Parse arguments
    set(options LINK_LIBRARY)
    set(oneValueArgs QUICKMORPHISM_DIR)
    set(multiValueArgs "")
    cmake_parse_arguments(QM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    
    if(QM_QUICKMORPHISM_DIR)
        # Add QuickMorphism as subdirectory
        add_subdirectory(${QM_QUICKMORPHISM_DIR} quickmorphism_build)
    endif()
    
    if(QM_LINK_LIBRARY)
        # Link QuickMorphism library
        target_link_libraries(${target_name} PRIVATE QuickMorphism)
    endif()
    
    # Configure the style
    configure_quickmorphism_style(${target_name} ${ARGN})
endfunction()