#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include "quickmorphism_config.h" // Auto-generated by CMake helpers

using namespace Qt::StringLiterals;

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);
    app.setApplicationName("QuickMorphism Example - Auto-configured");
    app.setApplicationVersion("1.0");

    QQmlApplicationEngine engine;
    
    // Use the helper function to automatically configure QuickMorphism
    QuickMorphism::setupStyle(engine);
    
    const QUrl url(u"qrc:/Demo_quickstyle.qml"_s);
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}